min_acl: public
clean: true
output: docs
author: iq3AddLi
github_url: https://github.com/iq3addLi/swift-vapor-layered-realworld-example-app
theme: fullwidth 
module: Domain // https://github.com/realm/jazzy/issues/382 🤔