version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_DATABASE: mysqldatabase
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
      MYSQL_ROOT_PASSWORD: rootpass
