//
// LoginUserRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoginUserRequest: Codable {

    public var user: LoginUser

    public init(user: LoginUser) {
        self.user = user
    }


}

