//
// NewArticleRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//


public struct NewArticleRequest: Codable {

    public var article: NewArticle

    public init(article: NewArticle) {
        self.article = article
    }


}

