//
// NewComment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NewComment: Codable {

    public var body: String

    public init(body: String) {
        self.body = body
    }


}

