//
// NewCommentRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NewCommentRequest: Codable {

    public var comment: NewComment

    public init(comment: NewComment) {
        self.comment = comment
    }


}

