//
// NewUserRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//


public struct NewUserRequest: Codable {

    public var user: NewUser

    public init(user: NewUser) {
        self.user = user
    }


}

