//
// UpdateArticleRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateArticleRequest: Codable {

    public var article: UpdateArticle

    public init(article: UpdateArticle) {
        self.article = article
    }


}

