//
// UpdateUserRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateUserRequest: Codable {

    public var user: UpdateUser

    public init(user: UpdateUser) {
        self.user = user
    }


}

