//
// GenericErrorModelErrors.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

/// see https://github.com/gothinkster/realworld/blob/master/api/swagger.json
public struct GenericErrorModelErrors: Codable {

    public var body: [String]

    public init(body: [String]) {
        self.body = body
    }

}
