//
// MultipleCommentsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

/// see https://github.com/gothinkster/realworld/blob/master/api/swagger.json
public struct MultipleCommentsResponse: Codable {

    public var comments: [Comment]

    public init(comments: [Comment]) {
        self.comments = comments
    }

}
