//
// ProfileResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

/// see https://github.com/gothinkster/realworld/blob/master/api/swagger.json
public struct ProfileResponse: Codable {

    public var profile: Profile

    public init(profile: Profile) {
        self.profile = profile
    }

}
