//
// UserResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

/// see https://github.com/gothinkster/realworld/blob/master/api/swagger.json
public struct UserResponse: Codable {

    public var user: User

    public init(user: User) {
        self.user = user
    }


}

