//
// Article.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Article: Codable {

    public var slug: String
    public var title: String
    public var _description: String
    public var body: String
    public var tagList: [String]
    public var createdAt: Date
    public var updatedAt: Date
    public var favorited: Bool
    public var favoritesCount: Int
    public var author: Profile

    public init(slug: String, title: String, _description: String, body: String, tagList: [String], createdAt: Date, updatedAt: Date, favorited: Bool, favoritesCount: Int, author: Profile) {
        self.slug = slug
        self.title = title
        self._description = _description
        self.body = body
        self.tagList = tagList
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.favorited = favorited
        self.favoritesCount = favoritesCount
        self.author = author
    }

    public enum CodingKeys: String, CodingKey { 
        case slug
        case title
        case _description = "description"
        case body
        case tagList
        case createdAt
        case updatedAt
        case favorited
        case favoritesCount
        case author
    }


}

