//
// Comment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Comment: Codable {

    public var _id: Int
    public var createdAt: Date
    public var updatedAt: Date
    public var body: String
    public var author: Profile

    public init(_id: Int, createdAt: Date, updatedAt: Date, body: String, author: Profile) {
        self._id = _id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.body = body
        self.author = author
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case createdAt
        case updatedAt
        case body
        case author
    }


}

