//
// GenericErrorModelErrors.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

// This definition does not match the content of the production environment
//public struct GenericErrorModelErrors: Codable {
//
//    public var body: [String]
//
//    public init(body: [String]) {
//        self.body = body
//    }
//
//
//}

