//
// GenericErrorModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//


public struct GenericErrorModel: Codable {

    public var errors: GenericErrorModelErrors

    public init(errors: GenericErrorModelErrors) {
        self.errors = errors
    }


}

