//
// MultipleArticlesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//


public struct MultipleArticlesResponse: Codable {

    public var articles: [Article]
    public var articlesCount: Int

    public init(articles: [Article], articlesCount: Int) {
        self.articles = articles
        self.articlesCount = articlesCount
    }
}
