//
// MultipleCommentsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//


public struct MultipleCommentsResponse: Codable {

    public var comments: [Comment]

    public init(comments: [Comment]) {
        self.comments = comments
    }


}

