//
// Profile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//


public struct Profile: Codable {

    public var username: String
    public var bio: String
    public var image: String
    public var following: Bool

    public init(username: String, bio: String, image: String, following: Bool) {
        self.username = username
        self.bio = bio
        self.image = image
        self.following = following
    }


}

