//
// SingleArticleResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SingleArticleResponse: Codable {

    public var article: Article

    public init(article: Article) {
        self.article = article
    }


}

