//
// SingleCommentResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SingleCommentResponse: Codable {

    public var comment: Comment

    public init(comment: Comment) {
        self.comment = comment
    }


}

