//
// TagsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//


public struct TagsResponse: Codable {

    public var tags: [String]

    public init(tags: [String]) {
        self.tags = tags
    }


}

