//
// LoginUserRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

/// see https://github.com/gothinkster/realworld/blob/master/api/swagger.json
public struct LoginUserRequest: Codable {

    public var user: LoginUser

    public init(user: LoginUser) {
        self.user = user
    }

}
