//
// NewArticleRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

/// see https://github.com/gothinkster/realworld/blob/master/api/swagger.json
public struct NewArticleRequest: Codable {

    public var article: NewArticle

    public init(article: NewArticle) {
        self.article = article
    }

}
