//
// NewCommentRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

/// see https://github.com/gothinkster/realworld/blob/master/api/swagger.json
public struct NewCommentRequest: Codable {

    public var comment: NewComment

    public init(comment: NewComment) {
        self.comment = comment
    }


}

