//
// NewUserRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

/// see https://github.com/gothinkster/realworld/blob/master/api/swagger.json
public struct NewUserRequest: Codable {

    public var user: NewUser

    public init(user: NewUser) {
        self.user = user
    }

}
