//
// UpdateUserRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

/// see https://github.com/gothinkster/realworld/blob/master/api/swagger.json
public struct UpdateUserRequest: Codable {

    public var user: UpdateUser

    public init(user: UpdateUser) {
        self.user = user
    }


}

