//
// UpdateArticleRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

/// see https://github.com/gothinkster/realworld/blob/master/api/swagger.json
public struct UpdateArticleRequest: Codable {

    public var article: UpdateArticle

    public init(article: UpdateArticle) {
        self.article = article
    }

}
